# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts-configmap
data:
  ngc_pull.sh: |-
{{ .Files.Get "files/ngc_pull.sh" | indent 4 }}
