{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nv-ingest.fullname" . }}
  labels:
    {{- include "nv-ingest.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nv-ingest.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
   {{- range .Values.autoscaling.metrics }}
      - {{- . | toYaml | nindent 10 }}
    {{- end }}
{{- end }}
