# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{ if and .Values.ngcSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api
type: Opaque
data:
  NGC_CLI_API_KEY: {{ template "nv-ingest.ngcAPIKey" . }}
  NGC_API_KEY: {{ template "nv-ingest.ngcAPIKey" . }}
{{- end }}


{{ if and .Values.imagePullSecret.name .Values.imagePullSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "nv-ingest.imagePullSecret" . }}
{{- end }}
