runs:
  - name: jp20_single
    dataset: jp20
    preset: single_gpu

  - name: bo20_single
    dataset: bo20
    preset: single_gpu

  # - name: bo767_single
  #   dataset: bo767
  #   preset: single_gpu
  # - name: earnings_single
  #   dataset: earnings
  #   preset: single_gpu
  # - name: financebench_single
  #   dataset: financebench
  #   preset: single_gpu
  # - name: bo10k_single
  #   dataset: bo10k
  #   preset: single_gpu
