# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set py_version = environ['CONDA_PY'] %}
{% set GIT_SHA = environ['GIT_SHA'] %}

# Determine Git root, falling back to default path ../../.. if Git is not available or the directory is not a Git repo
{% set git_root = environ.get('GIT_ROOT', '../../../src') %}

package:
  name: nv_ingest
  version: {{ environ.get('NV_INGEST_SERVICE_VERSION', 'Unknown') }}

source:
  path: {{ git_root }}

build:
  number: 0
  string: py{{ py_version }}_{{ GIT_SHA }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python=3.12.11
    - setuptools>=78.1.1
  run:
    - azure-core>=1.32.0
    - click>=8.1.7
    - fastapi>=0.115.6
    - fastparquet>=2024.11.0
    - fsspec>=2024.10.0
    - httpx>=0.28.1
    - isodate>=0.7.2
    - langdetect>=1.0.9
    - minio>=7.2.12
    - opentelemetry-api>=1.27.0
    - opentelemetry-exporter-otlp>=1.27.0
    - opentelemetry-sdk>=1.27.0
    - protobuf>=5.29.3
    - pydantic>=2.0.0
    - pypdfium2>=4.30.0,<5.0.0
    - pytest>=8.0.2
    - pytest-mock>=3.14.0
    - python>=3.12.11
    - python-docx>=1.1.2
    - python-dotenv>=1.0.1
    - python-magic>=0.4.27
    - python-pptx>=1.0.2
    - ray-all>=2.52.0
    - redis-py>=5.2.1
    - requests>=2.28.2
    - scipy>=1.15.1
    - setuptools>=78.1.1
    - tabulate>=0.9.0
    - tqdm>=4.67.1
    - transformers>=4.57.3
    # - unstructured-client>=0.25.9
    - uvicorn
    - universal_pathlib
  pip:
    - nvidia-riva-client==2.20.0
    - markitdown

  test:
    commands:
      - pytest ./tests

about:
  home: "https://github.com/NVIDIA/nv-ingest"
  license: "Apache-2.0"
  summary: "Python module supporting document ingestion."
  description: "Python module supporting document ingestion."

extra:
  recipe-maintainers:
    - drobison@nvidia.com

channels:
  - rapidsai
  - nvidia
  - conda-forge
