# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set py_version = environ['CONDA_PY'] %}
{% set GIT_SHA = environ['GIT_SHA'] %}

# Determine Git root, falling back to default path ../../.. if Git is not available or the directory is not a Git repo
{% set git_root = environ.get('GIT_ROOT', '../../../api') %}

package:
  name: nv_ingest_api
  version: {{ environ.get('NV_INGEST_API_VERSION', 'Unknown') }}

source:
  path: {{ git_root }}

build:
  number: 0
  string: py{{ py_version }}_{{ GIT_SHA }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python=3.12.11
    - setuptools>=78.1.1
  run:
    - aiohttp
    - backoff==2.2.1
    - diskcache>=5.6.3
    - fastparquet>=2024.11.0
    - ffmpeg-python==0.2.0
    - fsspec>=2025.5.1
    - glom
    - grpcio
    - langdetect>=1.0.9
    - librosa==0.10.2
    - minio>=7.2.12
    - numpy
    - pandas>=2.0
    - pillow
    - protobuf>=5.29.3  # intentional pin
    - pydantic>=2.0.0
    - py-opencv
    - pypdfium2>=4.30.0,<5  # TODO: migrate get_pos() -> get_bounds() and audit other v5 API changes
    - python>=3.12.11
    - python-dateutil
    - python-docx>=1.1.2
    - python-pptx>=1.0.2
    - redis-py>=5.2.1
    - requests>=2.28.2
    - scikit-learn>=1.6.0
    - scipy>=1.15.1
    - tqdm>=4.67.1
    - transformers>=4.47.0
    - universal-pathlib>=0.2.6
  pip:
    - nvidia-riva-client==2.20.0
    - markitdown
    - pymilvus>=2.5.10
    - tritonclient[grpc]
    - unstructured-client
  # Note: gpu extras (cudf) and llm extras (openai) are not available via conda; install via pip

  test:
    requires:
      - pytest>=8.0.2
      - pytest-mock>=3.14.0
      - moviepy==2.2.1
    commands:
      - pytest ./tests

about:
  home: "https://github.com/NVIDIA/nv-ingest"
  license: "Apache-2.0"
  summary: "Python module with core document ingestion functions."
  description: "Python module with core document ingestion functions."

extra:
  recipe-maintainers:
    - jdyer@nvidia.com

channels:
  - rapidsai
  - nvidia
  - conda-forge
