name: Setup Docker Buildx
description: Set up Docker Buildx with optional QEMU for multi-platform builds

inputs:
  use-qemu:
    description: 'Enable QEMU emulation for cross-platform builds'
    required: false
    default: 'false'
  platforms:
    description: 'Platforms to support (comma-separated)'
    required: false
    default: 'linux/amd64'

runs:
  using: composite
  steps:
    - name: Set up QEMU
      if: ${{ inputs.use-qemu == 'true' }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}
